trigger:
- development-eri

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  latestTag: 'latest'

stages:
- stage: Build
  displayName: Build Docker Image
  jobs:
  - job: Build
    displayName: Build and Push Image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        containerRegistry: 'docker'
        repository: 'erikrasniqi/energywise'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          $(latestTag)

- stage: TerraformInit
  displayName: Terraform Initialization
  jobs:
  - job: Init
    displayName: Terraform Init
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: TerraformCLI@2
      displayName: 'Terraform Init'
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        backendType: 'azurerm'
        backendServiceArm: 'azure-resource-manager-service-connection'
        backendAzureRmSubscriptionId: '09059aa9-15cd-4ad2-a4e7-864b5dc2ea35'
        ensureBackend: true
        backendAzureRmResourceGroupName: 'my-resource-group-bg'
        backendAzureRmResourceGroupLocation: 'East US'
        backendAzureRmStorageAccountName: 'storageaccounterikras'
        backendAzureRmContainerName: 'storageaccounterikrascontainer'
        backendAzureRmKey: 'kubernetes-dev.tfstate'
        allowTelemetryCollection: true

- stage: TerraformApply
  displayName: Terraform Apply
  dependsOn: TerraformInit
  jobs:
  - job: Apply
    displayName: Apply Terraform Changes
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadSecureFile@1
      name: publickey
      inputs:
        secureFile: 'azure_rsa.pub'

    - task: TerraformCLI@2
      displayName: 'Terraform Apply'
      inputs:
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        environmentServiceName: 'azure-resource-manager-service-connection'
        commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
        allowTelemetryCollection: true
