trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  latestTag: 'latest'
  
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build Image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'erikrasniqi-docker-hub'
        repository: 'erikrasniqi/energywise'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          $(latestTag)