trigger:
- development-eri

resources:
- repo: self


stages:
- stage: InstallAndRunAnsible
  displayName: Install and Run Ansible Playbooks
  jobs:
  - job: RunAnsible
    displayName: Run Ansible Playbooks
    pool:
      vmImage: 'ubuntu-latest' 
    steps:
    - task: DownloadSecureFile@1
      name: DownloadPrivateKey
      inputs:
        secureFile: 'azure_rsa.pub'  # Make sure this matches the name in Secure Files

    - script: |
        # Create .ssh directory if not exists
        mkdir -p ~/.ssh

        # Move the key to .ssh directory
        mv $(DownloadPrivateKey.secureFilePath) ~/.ssh/azure_rsa

        # Set correct permissions for the key
        chmod 600 ~/.ssh/azure_rsa

        # Add the key to SSH agent (optional, but helps with some setups)
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/azure_rsa
      displayName: 'Set SSH Key Permissions'

    - script: |
        # Run the Ansible playbook using the correct key
        ANSIBLE_CONFIG=$(System.DefaultWorkingDirectory)/ansible/ansible.cfg \
        ansible-playbook ansible/playbooks/docker-install.yml -i ansible/ansible_hosts
      displayName: 'Run Ansible Playbook'
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'False'  # Avoid host key verification issues