version: '3.9'
services:
  bike-mvc:
    image: erikrasniqi/bike-mvc:0.0.1.RELEASE
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - bike-db
    networks:
      - tour-network

  bike-db:
    image: erikrasniqi/bike-db:0.0.1.RELEASE
    ports:
      - "5432:5432"
    restart: always
    networks:
      - tour-network

networks:
  tour-network:

