- hosts: development  # Replace with your inventory group or host
  become: true
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist

    - name: Install Docker
      apt:
        name: docker.io  # Use docker.io for Ubuntu
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: ec2-user  # Change to your actual username if different
        groups: docker
        append: yes

    - name: Install Docker Compose
      shell: |
        curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      args:
        executable: /bin/bash
      become: true

    - name: Check Docker Compose version
      command: docker-compose version

    # playbooks/copy-docker-compose.yml

    - name: Copy docker-compose.yml to the VM
      copy:
        src: ../docker-compose.yml  # Adjust the path based on your repository structure
        dest: /home/azureuser/docker-compose.yml  # Path on the VM
        mode: '0644'  # Set file permissions
